version: 1.0.{build}

environment:
  NUGET_API_KEY:
    secure: oy2kluu6fhnrfh6ljl5apm7432tf5bguvkxvjvkmt66nni 
  gittoken:
    secure: Bg3Y9d7e4plyjf8voA+du0CzL2bcmVUdVybYm9oU1S1d1M4YV3gK6k5mVDtoyKYN
    
build_script:
- cmd: PowerShell -Version 2.0 .\build.ps1 -target "AppVeyor"
artifacts:
- path: nuget\*.nupkg
  name: Nuget
