//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("Cake.ProjHelpers")]
[assembly: AssemblyDescription("Cake AddIn to embed files into .proj files")]
[assembly: AssemblyCompany("Ori Almog")]
[assembly: AssemblyProduct("Cake.ProjHelpers")]
[assembly: AssemblyVersion("0.0.1")]
[assembly: AssemblyFileVersion("0.0.1")]
[assembly: AssemblyInformationalVersion("0.0.1")]
[assembly: AssemblyCopyright("Copyright © Ori Almog 2016")]
[assembly: CLSCompliant(true)]

